name: Build

on: [push]

env:
  BUILD_TYPE: MinSizeRel

jobs:

# === Raspberry PI PRO ===
  rpi-pro:
    runs-on: ubuntu-latest
    container: nesbox/rpi-tic80:latest

    steps:
    - uses: actions/checkout@v2
      with: 
        submodules: recursive
        fetch-depth: 0

    - name: Install Host toolchain
      run: |
        apt-get update
        apt-get install --assume-yes build-essential ruby-full

    - name: Build
      run: |
        cd build
        cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DBUILD_PRO=On -DCMAKE_TOOLCHAIN_FILE=rpi/toolchain.cmake ..
        cmake --build . --config $BUILD_TYPE --parallel
        cpack

    - name: Deploy DEB
      uses: actions/upload-artifact@v2
      with:
        name: 'tic80-rpi-deb-pro'
        path: build/tic80.deb

    - name: Deploy
      uses: actions/upload-artifact@v2
      with:
        name: 'tic80-rpi-pro'
        path: build/bin/tic80
